package com.jacaranda.model;

import java.util.List;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

@Entity
@Table(name="company")
public class Company {
	
	@Id
	@Column(name="id")
	private int id;
	@Column(name="name")
	private String name;
	@Column(name="address")
	private String address;
	@Column(name="city")
	private String city;
	
	@OneToMany(mappedBy="employeeCompany")
	private List<Employee> employees;
	
	@OneToMany(mappedBy="idCompany")
	private List<CompanyProject> projects;
	
	public Company() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	//FIELDS CONSTRUCTOR AUTOGENERATED
	//¿Modificar para que inicialice la lista de empleados a un List vacio?
	public Company(int id, String name, String address, String city, List<Employee> employees) {
		super();
		this.id = id;
		this.name = name;
		this.address = address;
		this.city = city;
		this.employees = employees;
	}



	//GETTERS & SETTERS AUTOGENERATED
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public List<Employee> getEmployees() {
		return employees;
	}

	public void setEmployees(List<Employee> employees) {
		this.employees = employees;
	}
	
	public List<CompanyProject> getProjects() {
		return projects;
	}
	
	public void setProjects(List<CompanyProject> projects) {
		this.projects = projects;
	}
	
	
	//HASCODE & EQUALS AUTOGENERATED ONLY ID


	@Override
	public int hashCode() {
		return Objects.hash(id);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Company other = (Company) obj;
		return id == other.id;
	}

	//TOSTRING AUTOGENERATED MODIFICATED
	@Override
	public String toString() {
		return "Company [id=" + id + ", name=" + name + ", address=" + address + ", city=" + city + ", employees="
				+ employees + "]";
	}

}
