package com.jacaranda.model;

import java.util.Objects;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Table(name="employeeProject")
public class EmployeeProject {
	
	@Id
	@ManyToOne
	@JoinColumn(name="idEmployee")
	private Employee idEmployee;
	@Id
	@ManyToOne
	@JoinColumn(name="idProject")
	private Project idProject;
	
	private int hours;
	
	//SUPERCLASS CONSTRUCTOR AUTOGENERATED
	public EmployeeProject() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	//FIELD CONSTRUCTOR AUTOGENERATED
	public EmployeeProject(Employee idEmployee, Project idProject, int hours) {
		super();
		this.idEmployee = idEmployee;
		this.idProject = idProject;
		this.hours = hours;
	}

	//GETTERS & SETTERS AUTOGENERATED
	public Employee getIdEmployee() {
		return idEmployee;
	}

	public void setIdEmployee(Employee idEmployee) {
		this.idEmployee = idEmployee;
	}

	public Project getIdProject() {
		return idProject;
	}

	public void setIdProject(Project idProject) {
		this.idProject = idProject;
	}

	public int getHours() {
		return hours;
	}

	public void setHours(int hours) {
		this.hours = hours;
	}

	//HASCODE & EQUALS (ONLY ID) AUTOGENERATED
	@Override
	public int hashCode() {
		return Objects.hash(idEmployee, idProject);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		EmployeeProject other = (EmployeeProject) obj;
		return Objects.equals(idEmployee, other.idEmployee) && Objects.equals(idProject, other.idProject);
	}
	
	

}
