package com.jacaranda.model;

import java.sql.Date;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

@Entity
@Table(name="employee")
public class Employee {
	
	@Id
	@Column(name="id")
	private int id;
	@Column(name="firstName")
	private String firstName;
	@Column(name="lastName")
	private String lastName;
	@Column(name="email")
	private String email;
	@Column(name="gender")
	private String gender;
	@Column(name="dateOfBirth")
	private Date dateOfBirth;
	@ManyToOne
	@JoinColumn(name="idCompany")
	private Company employeeCompany;
	
	public Employee() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	//FIELDS CONSTRUCTOR AUTOGENERATED
	public Employee(int id, String firstName, String lastName, String email, String gender, Date dateOfBirth,
			Company employeeCompany) {
		super();
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.employeeCompany = employeeCompany;
	}


	//GETTERS & SETTERS AUTOGENERATED
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Company getEmployeeCompany() {
		return employeeCompany;
	}

	public void setEmployeeCompany(Company employeeCompany) {
		this.employeeCompany = employeeCompany;
	}

	//HASCODE & EQUALS AUTOGENERATED ONLY ID
	@Override
	public int hashCode() {
		return Objects.hash(id);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Employee other = (Employee) obj;
		return id == other.id;
	}

	//TOSTRING AUTOGENERATED MODIFICATED
	@Override
	public String toString() {
		return "Employee [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", email=" + email
				+ ", gender=" + gender + ", dateOfBirth=" + dateOfBirth + ", employeeCompany=" + employeeCompany.getName() + "]";
	}
	
	
	

}
